#pragma once

#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN NO_PIN
#define SPI_SCK_PIN	GP2

#define LCD_RST_PIN GP13
#define LCD_DC_PIN GP14
#define LCD_CS_PIN GP15
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
