#pragma once

#undef SPI_DRIVER
#define SPI_DRIVER SPID0
#define SPI_MOSI_PIN GP3
#define SPI_SCK_PIN	GP2

#define LCD_RST_PIN GP13
#define LCD_DC_PIN GP14
#define LCD_CS_PIN GP15
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
